### ISSUE TITLE
Dependancy doesn't satisfy requirements

### ISSUE THREAD

**Issue by marvoh** [AdactiveSAS/saml2-bridge-bundle#10]
Unable to install anything above version 4.0 and here's why

Problem 1
    - Installation request for adactive-sas/saml2-bridge-bundle 0.7.1 -> satisfiable by adactive-sas/saml2-bridge-bundle[v0.7.1].
    - adactive-sas/saml2-bridge-bundle v0.7.1 requires roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master] but these conflict with your requirements or minimum-stability.

**Comment by moroine** [comment]
Hi,

You're right , I'll fix it by the end of the week. The issue is that this repository require roave/security-advisories which is not intended to be used into a library (just figure it out today thanks to your issue).

If you need to update now, you can change temporarily your minimum requirements. 

Another way would be to add also in your project that dependence (I'm not sure f it just give it a try). I really advice this repository which just make sure you haven't any dependence with a know security issue. If you read the README, you've understand why we need to always keep `dev-master`

**Comment by moroine** [comment]
Resolved into v0.8.0

**Comment by marvoh** [comment]
It worked, thank you!
