### ISSUE TITLE
Redirection with bad credentials

### ISSUE THREAD

**Issue by soromamadou** [AdactiveSAS/saml2-bridge-bundle#20]
Hello,
i got an issue when i give bad credential. It still redirect to the SP with an error: 
`The status code of the Response was not Success, was AuthnFailed
invalid_response
`
Do you know please, where is the problem ?

**Comment by moroine** [comment]
Hello,

It's because the SAML protocol expect to answer AuthnFailed when credentials are invalid. If you have a look (here)[https://github.com/AdactiveSAS/saml2-bridge-bundle/blob/master/src/SAML2/Provider/HostedIdentityProviderProcessor.php#L252] you can see that there is a option to increase the attempt limit.

So you just have to add this option in your `ServiceProvider` which will be used (here)[https://github.com/AdactiveSAS/saml2-bridge-bundle/blob/master/src/Entity/ServiceProvider.php#L133]

**Comment by soromamadou** [comment]
Hello,
thanks for reply
It works as expected.
